## 1.Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


## 2.Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [5]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types of elements in list_
print("Data types of elements in list_:")
for item in list_:
    print(type(item))

# Print data types of elements in array_list
print("\nData types of elements in array_list:")
for item in array_list:
    print(type(item))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


## 3.Considering the following changes in the variable, array_list:

In [7]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

print("Data types of elements in num_list:")
for row in num_list:
    for item in row:
        print(type(item))

print("\nData types of elements in num_array:")
for row in num_array:
    for item in row:
        print(type(item))


Data types of elements in num_list:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>

Data types of elements in num_array:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


## 4.Write a code to find the following characteristics of variable, num_array:

In [8]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Find the shape of num_array
shape = num_array.shape

# (ii) Find the size of num_array
size = num_array.size

print("(i) Shape of num_array:", shape)
print("(ii) Size of num_array:", size)


(i) Shape of num_array: (2, 3)
(ii) Size of num_array: 6


## 5.Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [9]:
import numpy as np

# Create a 3x3 matrix containing zeros
zeros_matrix = np.zeros((3, 3))

print(zeros_matrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## 6.Create an identity matrix of shape (5,5) using numpy functions?

In [10]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
